### PR TITLE
chore: run cargo fmt/cargo clippy. add github action

### PR DESCRIPTION
**Pull request by wcampbell0x2a**
Hey! want to use this library for one of my projects. Just running `rust fmt` on the code.

On that topic, would you be apposed to running `cargo fmt -- --check` to ensure all code is formatted correctly?

### CODE REVIEW

**Comment by wargio** [comment]
probably would be worth adding a check on the CI for this. @XVilka

**Comment by wcampbell0x2a** [comment]
Any updates on this?

**Review by XVilka — APPROVED** [review]
Sorry. Missed the notification. Could you please add this in CI? 

https://github.com/rizinorg/rz-pipe/blob/master/.github/workflows/ci.yml

**Comment by wcampbell0x2a** [comment]
> Sorry. Missed the notification. Could you please add this in CI?
> 
> https://github.com/rizinorg/rz-pipe/blob/master/.github/workflows/ci.yml

* Added `rustfmt` and `clippy` to github action ci
* Used suggestions from `cargo clippy` and ran `cargo fmt`

**Comment by wcampbell0x2a** [comment]
bump

**Pull request merged**
