### PR TITLE
Feature/rust remove unwrap

### PR DESCRIPTION
**Pull request by 4thel00z**
Addressed issues pointed out in https://github.com/rizinorg/rz-pipe/issues/11.

My rust is rusty though - no pun intended lel.

### CODE REVIEW

**Comment by spacemeowx2** [comment]
I would recommend [`thiserror`](http://docs.rs/thiserror) for defining Error type.

And I think it is ok to break API and bump version to `0.2.0`.

**Review by XVilka — CHANGES_REQUESTED** [review]
Agree with @spacemeowx2

**Comment by 4thel00z** [comment]
Thanks @spacemeowx2, @XVilka. Sure will give it a go in a few.

**Comment by 4thel00z** [comment]
I gave it another shot @spacemeowx2 / @XVilka. If it is not "rustonic" enough please point out what I can improve, I haven't touched rust in ages..

**Review by XVilka — APPROVED** [review]

**Comment by officialcjunior** [comment]
Thank you @4thel00z !
Awesome job.

**Pull request merged**
